# Enable debug logging, same as the "/butterfly debug" in game which can be activated at runtime. (admin only)
# Leave default, if you don't want your logs to be bombarded with Butterflies.
debug: false

# Rate-limit cooldown between each Butterfly command usage.
# Leave default (Recommended). Unless you are running a potato. 
cooldown:
  # Minimum time (in milliseconds).
  command_ms: 1000

# ActionBar Refresh time.
# Determines how often the ActionBar can refresh.
# Leave Default (Recommended).
actionbar:
  # Time (in milliseconds).
  refresh_ms: 1500

# Lifespan tracking.
# Determines how often lifespan data is saved to disk.
lifespan:
  # Time (in seconds).
  save_period_seconds: 300

# Flight behavior settings
# Change them as you like or keep default 
# These values has been tested from the start of this project to better match the concept of flying in survival
# and their trade-offs so if you think these aren't enough, experiment with your own values. 
flight:
  # Elytra durability consumed per second while flying (Vanilla Elytra fly consumes 1 durability per sec)
  durability_per_sec: 2

  # Hunger points consumed when enabling flight (Just like HP, 1 hunger bar = 2 points that means to drain full hunger, you need to set it to 20 hence it's the max value)
  hunger_cost_on_enable: 10 # Consumes 5 hunger bars

  # Default Vanilla flySpeed is 0.1
  speed: 0.05

  # If double-jumping mid air (while glue is still on), it negates fall damage as a default behaviour in vanilla for creative-like fly. 
  # This setting patches that by using "OUR VERY OWN DAMAGE CALCULATOR". 
  fall_damage: true